//AUTHENTICATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTHENTICATE = 'AUTHENTICATE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


//DAHSBOARD
export const GET_CARDS_START = 'GET_CARDS_START';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAIL = 'GET_CARDS_FAIL';

export const GET_HEALTHPOSTS_START = 'GET_HEALTHPOSTS_START';
export const GET_HEALTHPOSTS_SUCCESS = 'GET_HEALTHPOSTS_SUCCESS';
export const GET_HEALTHPOSTS_FAIL = 'GET_HEALTHPOSTS_FAIL';

export const GET_PLACES_START = 'GET_PLACES_START';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAIL = 'GET_PLACES_FAIL';


export const DELETE_USER = 'DELETE_USER';
export const ADD_USER = 'ADD_USER';
export const GET_USERS= 'GET_USERS';
export const USER_ERROR= 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

export const SET_INIT_URL = 'SET_INIT_URL';

export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const GET_WEATHER_DATA_START = 'GET_WEATHER_DATA_START';
export const SET_PLACES = 'SET_PLACES';

export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';
export const DARK_THEME = 'DARK_THEME';
export const DRAWER_TYPE = 'DRAWER_TYPE';
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
export const THEME_COLOR = 'THEME_COLOR';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const WINDOW_WIDTH = 'WINDOW_WIDTH';


export const FETCH_ACTIVE_DRONES_UPDATE = 'FETCH_ACTIVE_DRONES_UPDATE';
export const FETCH_ACTIVE_DRONES_SUCCESS = 'FETCH_ACTIVE_DRONES_SUCCESS';
export const FETCH_ACTIVE_DRONES_FAIL = 'FETCH_ACTIVE_DRONES_FAIL';

export const CHECKLIST_PASS = 'CHECKLIST_PASS';

export const FETCH_MISSION_LIST_UPDATE = 'FETCH_MISSION_LIST_UPDATE';
export const FETCH_MISSION_LIST_SUCCESS = 'FETCH_MISSION_LIST_SUCCESS';
export const FETCH_MISSION_LIST_FAIL = 'FETCH_MISSION_LIST_FAIL';

export const CREATE_MISSION = 'CREATE_MISSION';
export const UPDATE_MISSION = 'UPDATE_MISSION';
export const DELETE_MISSION = 'DELETE_MISSION';
export const GET_MISSION_START = 'DELETE_MISSION_START';
export const SET_MISSION = 'SET_MISSION';


export const GET_MEDICINES = 'GET_MEDICINES';
export const ADD_MEDICINE = 'ADD_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const UPDATE_ORDER = 'UPDATE_ORDER';

export const GET_DRONES = 'GET_DRONES'
export const ADD_DRONE = 'ADD_DRONE'
export const UPDATE_DRONE = 'UPDATE_DRONE';
export const GET_DRONE_DETAIL = 'GET_DRONE_DETAIL';

export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const MISSION_CREATE_LOADING = 'MISSION_CREATE_LOADING';

export const GET_MAINTENANCE = 'GET_MAINTENANCE'

export const GET_FLIGHTS = 'GET_FLIGHTS';
export const GET_FLIGHT_DETAILS = 'GET_FLIGHT_DETAILS';





